/home/rathel/.local/share/chezmoi/private_dot_local/bin/executable_wallpaper.sh.tmpl

diff --git a/private_dot_local/bin/executable_wallpaper.sh.tmpl b/private_dot_local/bin/executable_wallpaper.sh.tmpl
--- a/private_dot_local/bin/executable_wallpaper.sh.tmpl
+++ b/private_dot_local/bin/executable_wallpaper.sh.tmpl
@@ -4,20 +4,20 @@ sleep 2
 
 wallpapers="$HOME/Wallpapers"
 
-if command -v swww &> /dev/null; then
-	if ! pgrep -x "swww-daemon" > /dev/null; then
-		nohup swww-daemon >/dev/null 2>&1 &
+if command -v awww &> /dev/null; then
+	if ! pgrep -x "awww-daemon" > /dev/null; then
+		nohup awww-daemon >/dev/null 2>&1 &
 	fi
 else
-	echo "swww command not found. Please install swww to set the wallpaper."
+	echo "awww command not found. Please install awww to set the wallpaper."
 	exit 1
 fi
 
 while :; do
 	wallpaper1="$(fd . $wallpapers -e jpg -e png | shuf -n1)"
 	# wallpaper2="$(fd . $wallpapers -e jpg -e png | shuf -n1)"
-	swww img "$wallpaper1"
+	awww img "$wallpaper1"
 	# sleep 1
-	# swww img -o DP-2 "$wallpaper2"
+	# awww img -o DP-2 "$wallpaper2"
 	sleep 1h
 done
